"""
config.py — Phase 6 generation settings.

All knobs the recommendation engine needs, in one place. Model choices live
behind the ILLMProvider port, so switching provider never touches the logic.
"""
from __future__ import annotations

import os
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[3]
REPORTS_DIR = PROJECT_ROOT / "reports" / "phase6"

# Load a project-root .env (if present) so API keys can live in a git-ignored file
# instead of shell variables. Shell/OS variables still take precedence.
try:
    from dotenv import load_dotenv
    load_dotenv(PROJECT_ROOT / ".env")
except ImportError:  # python-dotenv optional; env vars still work without it
    pass

# --- LLM provider defaults ------------------------------------------------- #
# Provider-agnostic: local Ollama is the reproducible, offline default; the
# Anthropic adapter is available by switching `provider`.
DEFAULT_PROVIDER = "ollama"
OLLAMA_MODEL = "llama3.1"          # `ollama pull llama3.1`
ANTHROPIC_MODEL = "claude-sonnet-5"
# OpenRouter (OpenAI-compatible gateway). Needs OPENROUTER_API_KEY. Free-tier
# model slugs carry a ":free" suffix and change over time — override per request
# / via ASSAY? no: pass `model` explicitly, or set ASSAY_OPENROUTER_MODEL.
OPENROUTER_MODEL = os.getenv("ASSAY_OPENROUTER_MODEL", "tencent/hy3:free")
OPENROUTER_BASE_URL = "https://openrouter.ai/api/v1"

# Deterministic-as-possible generation → less drift, easier to ground/verify.
TEMPERATURE = 0.2
MAX_TOKENS = 2048

OPENROUTER_REASONING = {
    "effort": "none",
    "exclude": True,
}

# --- Retrieval ------------------------------------------------------------- #
TOP_K_EVIDENCE = 6                 # guideline passages injected into the prompt

# --- Groundedness verifier ------------------------------------------------- #
# Deterministic citation check always runs. The optional LLM entailment recheck
# ("is this advice supported by evidence Ei?") is heavier; off by default.
LLM_ENTAILMENT_RECHECK = False
# Minimum fraction of advice items that must be evidence-grounded for the report
# to be considered acceptable (surfaced as a Phase-9 metric, not a hard gate).
MIN_GROUNDEDNESS = 0.80

# --- Fixed safety text (system-owned, never generated by the LLM) ---------- #
DISCLAIMER = (
    "This report provides general, evidence-based lifestyle information derived "
    "from your blood test results. It is NOT a medical diagnosis and does not "
    "replace advice from a qualified healthcare professional. Discuss any "
    "changes, and any results that concern you, with your GP or clinician."
)
